### PR TITLE
add blocked by to model and bump version to 1.2.16

### PR DESCRIPTION
**Pull request by xinghengwang**

### CODE REVIEW

**Comment by xinghengwang** [comment]
not emergency. i forgot I need to add the field "blocked_by" to the event_model. or it type checks.

**Review by praves77 — APPROVED** [review]

**Comment by xinghengwang** [comment]
please go ahead and publish if you have credentials. @praves77  thanks

**Comment by praves77** [comment]
@xinghengwang sure will do.

**Comment by praves77** [comment]
@xinghengwang Published it
> gem push moesif_api-1.2.16.gem 
Pushing gem to https://rubygems.org...
Successfully registered gem: moesif_api (1.2.16)

**Comment by xinghengwang** [comment]
thank you.

**Pull request merged**
